import type { RslExpression, TypeRef } from "../model/index.js";
import type { TypeCompatibilityProfile } from "./types.js";

export interface TypeScriptAssertionOptions {
  readonly profile?: TypeCompatibilityProfile;
  readonly namedTypeMap?: string;
}

function typeScriptType(type: TypeRef, namedTypeMap: string): string {
  if (type.kind === "primitive") return type.name;
  if (type.kind === "named")
    return `${namedTypeMap}[${JSON.stringify(type.ref)}]`;
  if (type.kind === "array")
    return `ReadonlyArray<${typeScriptType(type.items, namedTypeMap)}>`;
  if (type.kind === "tuple")
    return `readonly [${type.items.map((item) => typeScriptType(item, namedTypeMap)).join(", ")}]`;
  if (type.kind === "record")
    return `{ readonly ${Object.entries(type.fields)
      .map(
        ([key, item]) =>
          `${JSON.stringify(key)}: ${typeScriptType(item, namedTypeMap)}`,
      )
      .join("; readonly ")} }`;
  if (type.kind === "union")
    return type.members
      .map((member) => typeScriptType(member, namedTypeMap))
      .join(" | ");
  if (type.kind === "generic")
    return `{ readonly __rslGeneric: ${namedTypeMap}[${JSON.stringify(type.ref)}]; readonly arguments: readonly [${type.arguments.map((argument) => typeScriptType(argument, namedTypeMap)).join(", ")}] }`;
  return `import("rxjs").Observable<${typeScriptType(type.value, namedTypeMap)}>`;
}

export function generateTypeScriptEdgeAssertions(
  expression: RslExpression,
  options: TypeScriptAssertionOptions = {},
): string {
  const profile = options.profile ?? "exact";
  const namedTypeMap = options.namedTypeMap ?? "RslNamedTypes";
  const nodes = new Map(expression.nodes.map((node) => [node.id, node]));
  const lines = [
    "// Generated by RxJS RSL. Supply the named-type map in this scope.",
    "type RslAssert<T extends true> = T;",
    "type RslAssignable<From, To> = [From] extends [To] ? true : false;",
    "type RslEqual<Left, Right> = RslAssignable<Left, Right> extends true ? (RslAssignable<Right, Left> extends true ? true : false) : false;",
    "",
  ];
  expression.edges.forEach((edge, edgeIndex) => {
    const source = nodes
      .get(edge.from.node)
      ?.outputs.find((port) => port.id === edge.from.port);
    const target = nodes
      .get(edge.to.node)
      ?.inputs.find((port) => port.id === edge.to.port);
    if (source === undefined || target === undefined) return;
    const relation = profile === "exact" ? "RslEqual" : "RslAssignable";
    lines.push(
      `type RslEdge${String(edgeIndex)} = RslAssert<${relation}<${typeScriptType(source.type, namedTypeMap)}, ${typeScriptType(target.type, namedTypeMap)}>>;`,
    );
  });
  return `${lines.join("\n")}\n`;
}
